#######################################
# Project Mode
# autogenerated file 
# DO NOT TOUCH 
#######################################
if { $argc != 2 } {
  exit
} else {
  set ena_syn  [lindex $argv 0]
  set ena_impl [lindex $argv 1]
}

